# Implementation of simple feed-forward neuron

In [1]:
import numpy as np

In [2]:
class Neuron(object):
    """
    A simple feed-forward artificial neuron.
    Args:
        num_inputs (int): The input vector size / number of input values.
    Attributes:
        W (ndarray): The weight values for each input.
    b (float): The bias value, added to the weighted sum.
    activation_func (callabel): The activation function.
    """
    def __init__(self, num_inputs, activation_func):
        super().__init__()
        # Randomly initializing the weight vector and the bias values
        self.W = np.random.rand(num_inputs)
        self.b = np.random.rand(1)
        self.activation_func = activation_func
        
    def forward(self, x):
        """Forward the input signal through the neuron"""
        z  = np.dot(x, self.W) + self.b
        return self.activation_func(z)

In [20]:
# Fixing the random number generator's seed, for reproducable results:
np.random.seed(42)

In [4]:
# Random input column array of 3 values (shape = `(1, 3)`)
x = np.random.rand(3).reshape(1, 3)

In [7]:
print(x)

[[0.37454012 0.95071431 0.73199394]]


In [15]:
# Instantianating a Perceptron
step_func = lambda y: 0 if y <= 0 else 1
perceptron = Neuron(num_inputs=x.size, activation_func=step_func)

In [18]:
perceptron.W

array([0.96990985, 0.83244264, 0.21233911])

In [19]:
perceptron.b

array([0.18182497])

In [13]:
out = perceptron.forward(x)

In [14]:
out

1